#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include "esp_err.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
    bool initialized;
    bool client_registered;
    bool device_present;
    bool device_open;
    bool interface_claimed;
    bool sample_rate_configured;
    bool streaming;

    uint8_t device_address;
    uint8_t interface_number;
    uint8_t alternate_setting;
    uint8_t endpoint;
    uint16_t max_packet_size;
    uint32_t sample_rate_hz;
    uint8_t channels;
    uint8_t bits_per_sample;
    uint16_t expected_packet_bytes; /* maximum packet bytes */
    uint16_t packet_bytes_min;
    uint16_t packet_bytes_max;

    uint32_t transfer_callbacks;
    uint32_t transfer_errors;
    uint32_t packets_total;
    uint32_t packets_completed;
    uint32_t packets_skipped;
    uint32_t packets_error;
    uint32_t packets_48_frames;
    uint64_t usb_bytes_sent;
    uint64_t source_frames_sent;
    uint64_t silence_frames_sent;

    uint32_t input_buffer_capacity;
    uint32_t input_buffered_bytes;
    uint32_t input_pushes;
    uint64_t input_bytes_received;
    uint64_t input_bytes_dropped_old;
    uint16_t input_peak_abs;
    uint64_t started_ms;
    uint64_t updated_ms;
    uint32_t disconnects;
    int last_error;
} ft710_audio_tx_status_t;

/** Start FT-710 UAC1 TX stream at 48 kHz stereo 16-bit using one 192-byte packet per 1 ms URB. PTT is not controlled. */
esp_err_t ft710_audio_tx_start(void);

/** Copy current UAC1 TX streaming status. */
void ft710_audio_tx_get_status(ft710_audio_tx_status_t *status);

/** Push browser microphone PCM at 48 kHz mono S16LE, duplicated to L/R for the radio.
 *  Low-latency microphone semantics: old queued PCM may be discarded when the
 *  queue is too deep. Do NOT use this for deterministic digital-mode audio. */
size_t ft710_audio_tx_push_mono_s16(const void *data, size_t bytes);

/** Push deterministic 48 kHz mono S16LE without ever discarding already queued PCM.
 *  Returns exactly bytes on success, or 0 when there is currently not enough
 *  queue space / the stream is unavailable. Intended for deterministic staged
 *  digital-mode playback where the producer must apply backpressure. */
size_t ft710_audio_tx_push_mono_s16_lossless(const void *data, size_t bytes);

/** Bounded FT8 Tune oscillator. Samples are generated by a dedicated producer
 *  task and pushed losslessly through the same mono stream buffer consumed by
 *  microphone/FT8 audio; synthesis no longer occurs in the USB callback. */
void ft710_audio_tx_tone_start(uint32_t frequency_hz, float level_dbfs);
void ft710_audio_tx_tone_start_1500(float level_dbfs);
void ft710_audio_tx_tone_set_level(float level_dbfs);
void ft710_audio_tx_tone_stop(void);
bool ft710_audio_tx_tone_active(void);


/** Discard queued browser microphone/audio PCM, causing USB TX to send silence. */
void ft710_audio_tx_input_reset(void);

#ifdef __cplusplus
}
#endif
